import styles from "@/styles/footer.module.scss"
import Image from "next/image"
import Header from "../Header/header"
import Footer from "../Footer/Footer"
import Head from "next/head"

export default function Abilties() {
    return (
        <>
            <Head>
                <title>Abilities</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/Naruto.ico" />
            </Head>
            <Header />
            <h2>ABILITIES</h2>
            <Footer />
        </>
    )
}