import Header from "../Header/header";
import Footer from "../Footer/Footer";
import Head from "next/head";
import { useState, useEffect } from "react";
import axios from "axios";

export default function Characters() {
    const [post, setPosts] = useState([]);
    const [nextPage, setNextPage] = useState(1);

    useEffect(() => {
        getPosts();
    }, [nextPage]);

    const getPosts = async () => {
        const response = await axios.get(
            `https://www.narutodb.xyz/api/character?page=${nextPage}&limit=30`
        );
        setPosts(response.data.characters);
    };

    const Personagens = (item, index) => {
        if (item.images.length === 0) {
            return null;
        }

        const imageUrl = item.images[0] ? item.images[0] : item.images[1];

        let nacionalidade = "";

        if (item.personal.affiliation === "Konohagakure") {
            nacionalidade = "Vila Oculta da Folha";
        } else if (item.personal.affiliation === "Kumogakure") {
            nacionalidade = "Vila Oculta da Nuvem";
        } else if (item.personal.affiliation === "Takigakure") {
            nacionalidade = "Vila Oculta da Cachoeira";
        } else if (item.personal.affiliation === "Sunagakure") {
            nacionalidade = "Vila Oculta da Areia";
        } else if (item.personal.affiliation === "Kirigakure") {
            nacionalidade = "Vila Oculta da Névoa";
        } else if (item.personal.affiliation === "Iwagakure") {
            nacionalidade = "Vila Oculta da Pedra";
        } else if (item.personal.affiliation === "Hoshigakure") {
            nacionalidade = "Vila Oculta da Estrela"
        } else if (item.personal.affiliation === "Kusagakure") {
            nacionalidade = "Vila Oculta da Grama"
        } else if (item.personal.affiliation === "Otogakure") {
            nacionalidade = "Vila Oculta do Som"
        } else if (item.personal.affiliation === "Yukigakure") {
            nacionalidade = "Vila Oculta da Neve"
        } else if (item.personal.affiliation === "Amegakure") {
            nacionalidade = "Vila Oculta da Chuva"
        } else if (item.personal.affiliation === "Mount Myōboku") {
            nacionalidade = "Monte Myōboku";
        }
        // criar um objeto com nome de todos os países e vilas e trazer pra cá comparando o valor vindo da API com valor do objeto
        window.scrollTo(750, 750)

        return (
            <figure key={index}>
                <img src={imageUrl} alt={item.name} />
                <figcaption>{item.name}</figcaption>
                <figcaption>{nacionalidade}</figcaption>
            </figure>
        );
    };

    return (
        <>
            <Head>
                <title>Characters</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/Naruto.ico" />
            </Head>
            <Header />
            {post.map((item, index) => Personagens(item, index))}

            <button onClick={() => { setNextPage((prevPage) => prevPage + 1)}}>
                Próxima página
            </button>

            <Footer />
        </>
    );
}
