import Head from 'next/head'
import Image from 'next/image'
import Header from '@/pages/Components/Header/header'
import { Anton, Hubballi } from "next/font/google"
import Footer from '@/pages/Components/Footer/Footer'
import Hokage_gif from "@/public/hokage.gif"
import Hokage_back from "@/public/hokage_back.jpg"
import styles from "@/styles/index.module.scss"
import { useState } from 'react'

const HubballiFont = Hubballi({
    subsets: ['latin'],
    weight: ['400']

})
const AntonFont = Anton({
  subsets: ['latin'],
  weight: ['400']

})

export default function Home() {

  const [narutoImage,setNarutoImage] = useState(Hokage_gif)

  const ChangeImage = () =>{
      setNarutoImage(narutoImage === Hokage_gif ? Hokage_back: Hokage_gif)
  }

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Naruto.ico" />
      </Head>
      <Header />
      
      <main className={styles.MainBox}>

        <h2 className={AntonFont.className}>HOME</h2>

        <section>
          <div onMouseOver={()=> ChangeImage()} onMouseOut={()=>{ChangeImage()}} className={styles.HokageBox} style={{backgroundImage:`url(${narutoImage.src})`}}></div>
          <p className={HubballiFont.className}>Naruto Uzumaki is a shinobi of Konohagakure's Uzumaki clan. He became the jinchūriki of the Nine-Tails on the day of his birth — a fate that caused him to be shunned by most of Konoha throughout his childhood. After joining Team Kakashi, Naruto worked hard to gain the village's acknowledgement all the while chasing his dream to become Hokage. In the following years, through many hardships and ordeals, he became a capable ninja, regarded as a hero both by the villagers, and soon after, the rest of the world, becoming known as the Hero of the Hidden Leaf. He soon proved to be one of the main factors in winning the Fourth Shinobi World War, leading him to achieve his dream and become the village's Seventh Hokage.</p>
        </section>

      </main>
      
      <Footer />
    </>
  )
}
